-- LLM plugins (currently disabled)
-- Uncomment and configure as needed

-- vim.pack.add { 'https://github.com/github/copilot.vim' }

-- Copilot.lua
-- vim.pack.add { 'https://github.com/zbirenbaum/copilot.lua' }
-- require('copilot').setup {
--   auto_confirm = false,
--   suggestion = { enabled = false },
--   panel = { enabled = false },
-- }

-- Minuet AI
-- vim.pack.add { 'https://github.com/nvim-lua/plenary.nvim' }
-- vim.pack.add { 'https://github.com/Saghen/blink.cmp' }
-- vim.pack.add { 'https://github.com/milanglacier/minuet-ai.nvim' }
-- require('minuet').setup {
--   keymap = {
--     ['<leader>a'] = require('minuet').make_blink_map(),
--   },
--   provider = 'openai_fim_compatible',
--   n_completions = 1,
--   context_window = 512,
--   provider_options = {
--     openai_fim_compatible = {
--       api_key = 'TERM',
--       name = 'Ollama',
--       end_point = 'http://localhost:11434/v1/completions',
--       model = 'qwen2.5-coder:7b',
--       optional = {
--         max_tokens = 56,
--         top_p = 0.9,
--       },
--     },
--   },
-- }

-- Gemini.nvim
-- vim.pack.add { 'https://github.com/kiddos/gemini.nvim' }
-- require('gemini').setup {}

-- Bropilot
-- vim.pack.add { 'https://github.com/nvim-lua/plenary.nvim' }
-- vim.pack.add { 'https://github.com/j-hui/fidget.nvim' }
-- vim.pack.add { 'https://github.com/meeehdi-dev/bropilot.nvim' }
-- require('bropilot').setup {
--   auto_suggest = true,
--   model = 'qwen2.5-coder:7b',
--   keymap = {},
-- }
